@echo off
setlocal EnableExtensions
cd /d "%~dp0"

goto :Preparing
:Zapusk
cls

for /f %%a in ('echo prompt $E^| cmd') do set "ESC=%%a"

echo                         %ESC%[90m______                ____            _____                         __ 
echo                        / ____/___  ____  ____/ / /_  __  ____/__  /  ____ _____  ________  / /_
echo                       / / __/ __ \/ __ \/ __  / __ \/ / / / _ \/ /  / __ `/ __ \/ ___/ _ \/ __/
echo                      / /_/ / /_/ / /_/ / /_/ / /_/ / /_/ /  __/ /__/ /_/ / /_/ / /  /  __/ /_ 
echo                      \____/\____/\____/\__,_/_.___/\__, /\___/____/\__,_/ .___/_/   \___/\__/
echo                                                   /____/               /_/

:: Пути указываем относительно папки configs (на уровень выше)
for %%I in ("%~dp0..\..") do set "ProjectDir=%%~fI"
set "FAKE=%ProjectDir%\bin\fake\"
set "BIN=%ProjectDir%\bin\"
set "LISTS=%ProjectDir%\%lists\"

set "CDN_BypassLevel=base"

set "CONFIG_NAME=CONFIGURATOR_made"
echo Config: %CONFIG_NAME%
title GoodbyeZapret:  %CONFIG_NAME%
echo.
echo Winws:

:: --- Generated by builder.exe ---

"%BIN%winws2.exe" ^
--lua-init=@"%BIN%lua\zapret-lib.lua" --lua-init=@"%BIN%lua\zapret-antidpi.lua" --lua-init=@"%BIN%lua\custom_funcs.lua" ^
--wf-tcp-out=80,443,444-65535 --wf-udp-out=443 ^
--wf-raw-part=@"%BIN%windivert.filter\windivert_part.discord_media.txt" ^
--wf-raw-part=@"%BIN%windivert.filter\windivert_part.stun.txt" ^
--wf-raw-part=@"%BIN%windivert.filter\windivert_part.wireguard.txt" ^
--blob=fake_default_udp:0x00000000000000000000000000000000 ^
--blob=fake_quic_1:@"%FAKE%fake_quic_1.bin" ^
--blob=fake_tls_2:@"%FAKE%fake_tls_2.bin" ^
--blob=fake_tls_4:@"%FAKE%fake_tls_4.bin" ^
--blob=quic_google:@"%FAKE%quic_initial_www_google_com.bin" ^
--blob=tls5:@"%FAKE%fake_tls_5.bin" ^
--blob=quic_initial_www_google_com:@"%FAKE%quic_initial_www_google_com.bin" ^
--blob=tls_www_google:@"%FAKE%tls_clienthello_www_google_com.bin" ^
--filter-l7=discord,wireguard,stun --out-range=-d10 --lua-desync=fake:blob=fake_default_udp --new ^
--filter-tcp=443 --filter-l7=unknown --hostlist="%LISTS%russia-youtube-rtmps.txt" --out-range=-n3 --payload=tls_client_hello --lua-desync=multisplit:seqovl_pattern=fake_tls_2:seqovl=228 --new ^
--filter-tcp=80,443 --out-range=-d10 --hostlist="%LISTS%list-youtube.txt" --payload=tls_client_hello --lua-desync=multisplit:pos=midsld-1:seqovl=1 --new ^
--filter-udp=443 --hostlist-domains=yt3.ggpht.com,www.youtube.com,signaler-pa.youtube.com --out-range=-d9 --payload=quic_initial --lua-desync=fake:blob=0x0c000000:blob=fake_quic_1:ip_ttl=6 --new ^
--filter-tcp=80,443 --hostlist-domains=googlevideo.com --payload=tls_client_hello --out-range=-d10 --lua-desync=multisplit:seqovl=211:seqovl_pattern=fake_tls_4 --new ^
--filter-tcp=443 --hostlist-domains=updates.discord.com --lua-desync=wssize:wsize=1:scale=6 --lua-desync=syndata --payload tls_client_hello --lua-desync=multisplit --new ^
--filter-tcp=443,2053,2083,2087,2096,8443 --hostlist="%LISTS%list-discord.txt" --out-range=-n3 --payload=tls_client_hello --lua-desync=multisplit:seqovl_pattern=fake_tls_2:seqovl=228 --new ^
--filter-udp=443 --hostlist="%LISTS%list-discord.txt" --payload=unknown --out-range=-n2 --lua-desync=fake:blob=quic_google:repeats=9:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=unknown --new ^
--filter-tcp=443,444-65535 --hostlist-domains=awsglobalaccelerator.com,cloudfront.net,amazon.com,amazonaws.com,awsstatic.com,epicgames.com --out-range=-n5 --payload=tls_client_hello --lua-desync=fake:blob=0x1603:tls_mod=rnd,dupsid,sni=fonts.google.com --lua-desync=fake:blob=tls_www_google:tls_mod=rnd,dupsid,sni=fonts.google.com --lua-desync=multisplit:seqovl_pattern=fake_tls_4:pos=1:seqovl=314 --new ^
--filter-tcp=443,444-65535 --hostlist-domains=awsglobalaccelerator.com,cloudfront.net,amazon.com,amazonaws.com,awsstatic.com,epicgames.com --out-range=-n5 --payload=http_req --lua-desync=fake:blob=0x1603:blob=!+2:tls_mod=rnd,dupsid,sni=fonts.google.com:ip_id=seq --lua-desync=fakedsplit:pos=method+2:tcp_ack=-66000:tcp_ts_up --lua-desync=multisplit:seqovl_pattern=fake_tls_4:pos=1 --new ^
--filter-tcp=80,443,444-65535 --ipset="%LISTS%ipset-cloudflare-%CDN_BypassLevel%.txt" --payload=tls_client_hello --out-range=-d10 --lua-desync=multisplit:seqovl=211:seqovl_pattern=tls5 --new ^
--filter-udp=443,444-65535 --ipset="%LISTS%ipset-cloudflare-%CDN_BypassLevel%.txt" --payload=unknown --out-range=-n2 --lua-desync=fake:blob=quic_google:repeats=2:payload=unknown --new ^
--filter-tcp=2053,2083,2087,2096,8443 --filter-l7=tls --out-range=-n5 --payload=tls_client_hello --lua-desync=rst:tcp_md5sig=1:tcp_seq=-10000:tcp_ack=-66000 --lua-desync=multidisorder:pos=3:tcp_md5sig=1:tcp_seq=-10000:tcp_ack=-66000 --new ^
--filter-udp=5056,27002 --out-range=-n15 --payload=quic_initial --lua-desync=fake:blob=@quic_initial_www_google_com.bin:repeats=6 --new ^
--filter-tcp=80,443,6568 --ipset="%LISTS%ipset-anydesk.txt" --out-range=-d10 --lua-desync=multisplit:seqovl=211:seqovl_pattern=tls5


REM Проверяем, существует ли GoodbyeZapretTray.exe перед запуском
if exist "%ProjectDir%tools\tray\GoodbyeZapretTray.exe" (
    tasklist /FI "IMAGENAME eq GoodbyeZapretTray.exe" 2>NUL | find /I /N "GoodbyeZapretTray.exe" >NUL
    if errorlevel 1 (
        start "" "%ProjectDir%tools\tray\GoodbyeZapretTray.exe"
    )
)

goto :EOF


:Preparing
if not "%1"=="am_admin" (
  powershell -Command "Start-Process -FilePath '%~f0' -ArgumentList 'am_admin' -Verb RunAs"
  exit /b
)
Echo Preparing...

REM Stop & delete zapret service if it exists
sc query "zapret" >nul 2>&1
if %errorlevel% equ 0 (
  sc stop zapret >nul 2>&1
  sc delete zapret >nul 2>&1
)

REM Check if winws.exe is running and terminate it if found
tasklist /FI "IMAGENAME eq winws.exe" 2>NUL | find /I /N "winws.exe" >NUL
if "%ERRORLEVEL%"=="0" (
  REM Forcefully kill winws.exe process
  taskkill /F /IM winws.exe >nul 2>&1
)

REM Check if winws2.exe is running and terminate it if found
tasklist /FI "IMAGENAME eq winws2.exe" 2>NUL | find /I /N "winws2.exe" >NUL
if "%ERRORLEVEL%"=="0" (
  REM Forcefully kill winws2.exe process
  taskkill /F /IM winws2.exe >nul 2>&1
)

REM Flush DNS cache
ipconfig /flushdns > nul
cls
goto :Zapusk
